// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using YemekSiparis.DAL.Context;

#nullable disable

namespace YemekSiparis.DAL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20231112221108_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("YemekSiparis.Core.Entities.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ConfirmCode")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "1",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "f4868d49-ac84-4a83-92b5-d7bea234ab0c",
                            ConfirmCode = 0,
                            Email = "eren.colk01@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "d7f0aa36-b5cc-4d68-9b1d-b5a57a76644e",
                            TwoFactorEnabled = false,
                            UserName = "erencolak"
                        });
                });

            modelBuilder.Entity("YemekSiparis.Core.Entities.Beverage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsSelected")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Beverages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2023, 11, 13, 1, 11, 8, 296, DateTimeKind.Local).AddTicks(4636),
                            DeletedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsSelected = false,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Kola",
                            Price = 12.00m,
                            Status = 1,
                            Stock = 30
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2023, 11, 13, 1, 11, 8, 296, DateTimeKind.Local).AddTicks(4649),
                            DeletedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsSelected = false,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Ayran",
                            Price = 8.50m,
                            Status = 1,
                            Stock = 45
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2023, 11, 13, 1, 11, 8, 296, DateTimeKind.Local).AddTicks(4652),
                            DeletedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsSelected = false,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Soda",
                            Price = 6.00m,
                            Status = 1,
                            Stock = 53
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2023, 11, 13, 1, 11, 8, 296, DateTimeKind.Local).AddTicks(4654),
                            DeletedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsSelected = false,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Su",
                            Price = 4.50m,
                            Status = 1,
                            Stock = 46
                        });
                });

            modelBuilder.Entity("YemekSiparis.Core.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2023, 11, 13, 1, 11, 8, 296, DateTimeKind.Local).AddTicks(4718),
                            DeletedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Hamburger",
                            Status = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2023, 11, 13, 1, 11, 8, 296, DateTimeKind.Local).AddTicks(4722),
                            DeletedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Pizza",
                            Status = 1
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2023, 11, 13, 1, 11, 8, 296, DateTimeKind.Local).AddTicks(4724),
                            DeletedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Makarna",
                            Status = 1
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2023, 11, 13, 1, 11, 8, 296, DateTimeKind.Local).AddTicks(4726),
                            DeletedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Döner",
                            Status = 1
                        });
                });

            modelBuilder.Entity("YemekSiparis.Core.Entities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Age")
                        .HasColumnType("int");

                    b.Property<string>("AppUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("Birthdate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId")
                        .IsUnique();

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Seyhan /ADANA",
                            Age = 30,
                            AppUserId = "1",
                            Birthdate = new DateTime(1992, 12, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedDate = new DateTime(2023, 11, 13, 1, 11, 8, 296, DateTimeKind.Local).AddTicks(4794),
                            DeletedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gender = 1,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Eren ÇOLAK",
                            Status = 1
                        });
                });

            modelBuilder.Entity("YemekSiparis.Core.Entities.Diet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Diets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2023, 11, 13, 1, 11, 8, 296, DateTimeKind.Local).AddTicks(4854),
                            DeletedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Sağlıkla Tüketebilirsiniz",
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Glutensiz",
                            Status = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2023, 11, 13, 1, 11, 8, 296, DateTimeKind.Local).AddTicks(4859),
                            DeletedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Hayvanları koruyalım ve sevelim",
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Vejeteryan",
                            Status = 1
                        });
                });

            modelBuilder.Entity("YemekSiparis.Core.Entities.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Shift")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Şakirpaşa/ADANA",
                            CreatedDate = new DateTime(2023, 11, 13, 1, 11, 8, 296, DateTimeKind.Local).AddTicks(4920),
                            DeletedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Cabbar HÜSEYİN",
                            Role = "Kasiyer",
                            Salary = 11.500m,
                            Shift = "Gündüz",
                            Status = 1
                        },
                        new
                        {
                            Id = 2,
                            Address = "Hürriyet/ADANA",
                            CreatedDate = new DateTime(2023, 11, 13, 1, 11, 8, 296, DateTimeKind.Local).AddTicks(4924),
                            DeletedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Ayşe FATMA",
                            Role = "Temizlikçi",
                            Salary = 11.500m,
                            Shift = "Gündüz",
                            Status = 1
                        });
                });

            modelBuilder.Entity("YemekSiparis.Core.Entities.Extra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsSelected")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Extras");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2023, 11, 13, 1, 11, 8, 296, DateTimeKind.Local).AddTicks(5014),
                            DeletedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsSelected = false,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Buffalo Sos",
                            Price = 4.99m,
                            Status = 1,
                            Stock = 164
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2023, 11, 13, 1, 11, 8, 296, DateTimeKind.Local).AddTicks(5018),
                            DeletedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsSelected = false,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Ketçap",
                            Price = 2.99m,
                            Status = 1,
                            Stock = 545
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2023, 11, 13, 1, 11, 8, 296, DateTimeKind.Local).AddTicks(5020),
                            DeletedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsSelected = false,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Mayonez",
                            Price = 2.99m,
                            Status = 1,
                            Stock = 454
                        });
                });

            modelBuilder.Entity("YemekSiparis.Core.Entities.Food", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CategoryID")
                        .HasColumnType("int");

                    b.Property<int>("ClickCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Discount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<byte[]>("Image")
                        .HasColumnType("varbinary(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PrepTime")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("Rating")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryID");

                    b.ToTable("Foods");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryID = 1,
                            ClickCount = 0,
                            CreatedDate = new DateTime(2023, 11, 13, 1, 11, 8, 296, DateTimeKind.Local).AddTicks(6070),
                            DeletedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "110 gr. Helal Dana Eti, Cheader Peyniri, Karamelize Soğan",
                            Discount = 0m,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "SteakHouse",
                            PrepTime = 20,
                            Price = 120m,
                            Status = 1,
                            Stock = 20
                        },
                        new
                        {
                            Id = 2,
                            CategoryID = 2,
                            ClickCount = 0,
                            CreatedDate = new DateTime(2023, 11, 13, 1, 11, 8, 296, DateTimeKind.Local).AddTicks(6077),
                            DeletedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Mozeralla,Domates",
                            Discount = 0m,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Margarita Bol Malzemos",
                            PrepTime = 24,
                            Price = 110m,
                            Status = 1,
                            Stock = 30
                        },
                        new
                        {
                            Id = 3,
                            CategoryID = 3,
                            ClickCount = 0,
                            CreatedDate = new DateTime(2023, 11, 13, 1, 11, 8, 296, DateTimeKind.Local).AddTicks(6079),
                            DeletedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Penne Sosu, Krema",
                            Discount = 0m,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Penne Soslu Makarna",
                            PrepTime = 30,
                            Price = 125m,
                            Status = 1,
                            Stock = 45
                        },
                        new
                        {
                            Id = 4,
                            CategoryID = 1,
                            ClickCount = 0,
                            CreatedDate = new DateTime(2023, 11, 13, 1, 11, 8, 296, DateTimeKind.Local).AddTicks(6081),
                            DeletedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "180 gr. Dana köfte, cheddar peyniri, marul, domates, turşu",
                            Discount = 0m,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Classic Burger",
                            PrepTime = 15,
                            Price = 90m,
                            Status = 1,
                            Stock = 25
                        },
                        new
                        {
                            Id = 7,
                            CategoryID = 2,
                            ClickCount = 0,
                            CreatedDate = new DateTime(2023, 11, 13, 1, 11, 8, 296, DateTimeKind.Local).AddTicks(6084),
                            DeletedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Mozeralla, pepperoni sosis, pizza sosu",
                            Discount = 0m,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Pepperoni Pizza",
                            PrepTime = 22,
                            Price = 100m,
                            Status = 1,
                            Stock = 40
                        },
                        new
                        {
                            Id = 12,
                            CategoryID = 3,
                            ClickCount = 0,
                            CreatedDate = new DateTime(2023, 11, 13, 1, 11, 8, 296, DateTimeKind.Local).AddTicks(6087),
                            DeletedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Spagetti makarna, jambon, yumurta sarısı, parmesan peyniri, krema",
                            Discount = 0m,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Spaghetti Carbonara",
                            PrepTime = 25,
                            Price = 130m,
                            Status = 1,
                            Stock = 35
                        },
                        new
                        {
                            Id = 17,
                            CategoryID = 4,
                            ClickCount = 0,
                            CreatedDate = new DateTime(2023, 11, 13, 1, 11, 8, 296, DateTimeKind.Local).AddTicks(6110),
                            DeletedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Adana usulü dana kıyma, baharatlar, lavaş",
                            Discount = 0m,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Adana Kebab",
                            PrepTime = 35,
                            Price = 150m,
                            Status = 1,
                            Stock = 50
                        },
                        new
                        {
                            Id = 5,
                            CategoryID = 1,
                            ClickCount = 0,
                            CreatedDate = new DateTime(2023, 11, 13, 1, 11, 8, 296, DateTimeKind.Local).AddTicks(6112),
                            DeletedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "200 gr. Dana köfte, cheddar, mozeralla, peynir sosu, marul, domates",
                            Discount = 0m,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Cheese Lover's Burger",
                            PrepTime = 18,
                            Price = 95m,
                            Status = 1,
                            Stock = 15
                        },
                        new
                        {
                            Id = 6,
                            CategoryID = 1,
                            ClickCount = 0,
                            CreatedDate = new DateTime(2023, 11, 13, 1, 11, 8, 296, DateTimeKind.Local).AddTicks(6115),
                            DeletedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "180 gr. Dana köfte, bacon, barbekü sos, cheddar, marul, turşu",
                            Discount = 0m,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "BBQ Bacon Burger",
                            PrepTime = 20,
                            Price = 110m,
                            Status = 1,
                            Stock = 18
                        },
                        new
                        {
                            Id = 8,
                            CategoryID = 2,
                            ClickCount = 0,
                            CreatedDate = new DateTime(2023, 11, 13, 1, 11, 8, 296, DateTimeKind.Local).AddTicks(6118),
                            DeletedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Mozeralla, biber, mantar, siyah zeytin, mısır, domates",
                            Discount = 0m,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Vegetarian Delight Pizza",
                            PrepTime = 25,
                            Price = 95m,
                            Status = 1,
                            Stock = 28
                        },
                        new
                        {
                            Id = 9,
                            CategoryID = 2,
                            ClickCount = 0,
                            CreatedDate = new DateTime(2023, 11, 13, 1, 11, 8, 296, DateTimeKind.Local).AddTicks(6120),
                            DeletedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Mozeralla, karides, kalamar, midye, sarımsak, roka",
                            Discount = 0m,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Seafood Supreme Pizza",
                            PrepTime = 28,
                            Price = 120m,
                            Status = 1,
                            Stock = 32
                        },
                        new
                        {
                            Id = 13,
                            CategoryID = 3,
                            ClickCount = 0,
                            CreatedDate = new DateTime(2023, 11, 13, 1, 11, 8, 296, DateTimeKind.Local).AddTicks(6123),
                            DeletedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Ravioli, tereyağlı adaçayı sosu, parmesan peyniri",
                            Discount = 0m,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Ravioli with Sage Butter",
                            PrepTime = 22,
                            Price = 135m,
                            Status = 1,
                            Stock = 40
                        },
                        new
                        {
                            Id = 14,
                            CategoryID = 3,
                            ClickCount = 0,
                            CreatedDate = new DateTime(2023, 11, 13, 1, 11, 8, 296, DateTimeKind.Local).AddTicks(6125),
                            DeletedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Karides, sarımsak, limon sos, fettuccine makarna",
                            Discount = 0m,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Lemon Garlic Shrimp Pasta",
                            PrepTime = 30,
                            Price = 140m,
                            Status = 1,
                            Stock = 38
                        },
                        new
                        {
                            Id = 18,
                            CategoryID = 4,
                            ClickCount = 0,
                            CreatedDate = new DateTime(2023, 11, 13, 1, 11, 8, 296, DateTimeKind.Local).AddTicks(6127),
                            DeletedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Döner et, yoğurt, domates sosu, tereyağlı ekmek",
                            Discount = 0m,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Iskender Kebab",
                            PrepTime = 40,
                            Price = 160m,
                            Status = 1,
                            Stock = 22
                        },
                        new
                        {
                            Id = 19,
                            CategoryID = 4,
                            ClickCount = 0,
                            CreatedDate = new DateTime(2023, 11, 13, 1, 11, 8, 296, DateTimeKind.Local).AddTicks(6130),
                            DeletedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Tavuk şiş, baharatlar, pilav, acılı sos",
                            Discount = 0m,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Chicken Shish Kebab",
                            PrepTime = 35,
                            Price = 145m,
                            Status = 1,
                            Stock = 25
                        },
                        new
                        {
                            Id = 21,
                            CategoryID = 1,
                            ClickCount = 0,
                            CreatedDate = new DateTime(2023, 11, 13, 1, 11, 8, 296, DateTimeKind.Local).AddTicks(6132),
                            DeletedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "180 gr. Acılı dana köfte, jalapeño biber, pepper jack peyniri, marul, domates",
                            Discount = 0m,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Spicy Jalapeño Burger",
                            PrepTime = 18,
                            Price = 100m,
                            Status = 1,
                            Stock = 20
                        },
                        new
                        {
                            Id = 22,
                            CategoryID = 1,
                            ClickCount = 0,
                            CreatedDate = new DateTime(2023, 11, 13, 1, 11, 8, 296, DateTimeKind.Local).AddTicks(6134),
                            DeletedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "200 gr. Dana köfte, mantar, swiss peyniri, hardal, turşu",
                            Discount = 0m,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Mushroom Swiss Burger",
                            PrepTime = 20,
                            Price = 110m,
                            Status = 1,
                            Stock = 18
                        },
                        new
                        {
                            Id = 23,
                            CategoryID = 2,
                            ClickCount = 0,
                            CreatedDate = new DateTime(2023, 11, 13, 1, 11, 8, 296, DateTimeKind.Local).AddTicks(6137),
                            DeletedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Mozeralla, domates, taze fesleğen, trüf yağı",
                            Discount = 0m,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Margherita with Truffle Oil",
                            PrepTime = 22,
                            Price = 120m,
                            Status = 1,
                            Stock = 25
                        },
                        new
                        {
                            Id = 24,
                            CategoryID = 2,
                            ClickCount = 0,
                            CreatedDate = new DateTime(2023, 11, 13, 1, 11, 8, 296, DateTimeKind.Local).AddTicks(6139),
                            DeletedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Tavuk, barbekü sos, ranch sos, mozeralla, soğan",
                            Discount = 0m,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "BBQ Chicken Ranch Pizza",
                            PrepTime = 25,
                            Price = 130m,
                            Status = 1,
                            Stock = 30
                        },
                        new
                        {
                            Id = 25,
                            CategoryID = 3,
                            ClickCount = 0,
                            CreatedDate = new DateTime(2023, 11, 13, 1, 11, 8, 296, DateTimeKind.Local).AddTicks(6141),
                            DeletedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Linguine makarna, pesto sos, taze parmesan peyniri",
                            Discount = 0m,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Linguine with Pesto Genovese",
                            PrepTime = 20,
                            Price = 125m,
                            Status = 1,
                            Stock = 35
                        },
                        new
                        {
                            Id = 26,
                            CategoryID = 3,
                            ClickCount = 0,
                            CreatedDate = new DateTime(2023, 11, 13, 1, 11, 8, 296, DateTimeKind.Local).AddTicks(6143),
                            DeletedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Fettuccine makarna, kremsi sarımsaklı mantar sos, parmesan peyniri",
                            Discount = 0m,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Creamy Garlic Mushroom Fettuccine",
                            PrepTime = 28,
                            Price = 135m,
                            Status = 1,
                            Stock = 32
                        },
                        new
                        {
                            Id = 27,
                            CategoryID = 4,
                            ClickCount = 0,
                            CreatedDate = new DateTime(2023, 11, 13, 1, 11, 8, 296, DateTimeKind.Local).AddTicks(6145),
                            DeletedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Tavuk, dana, kuzu şiş, baharatlar, közlenmiş sebzeler, pilav",
                            Discount = 0m,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Mixed Grill Kebab",
                            PrepTime = 40,
                            Price = 155m,
                            Status = 1,
                            Stock = 28
                        },
                        new
                        {
                            Id = 28,
                            CategoryID = 4,
                            ClickCount = 0,
                            CreatedDate = new DateTime(2023, 11, 13, 1, 11, 8, 296, DateTimeKind.Local).AddTicks(6147),
                            DeletedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Falafel, humus, taze sebzeler, lavaş",
                            Discount = 0m,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Vegetarian Falafel Wrap",
                            PrepTime = 35,
                            Price = 140m,
                            Status = 1,
                            Stock = 22
                        });
                });

            modelBuilder.Entity("YemekSiparis.Core.Entities.FoodDiet", b =>
                {
                    b.Property<int>("DietID")
                        .HasColumnType("int");

                    b.Property<int>("FoodID")
                        .HasColumnType("int");

                    b.HasKey("DietID", "FoodID");

                    b.HasIndex("FoodID");

                    b.ToTable("FoodDiets");

                    b.HasData(
                        new
                        {
                            DietID = 1,
                            FoodID = 1
                        },
                        new
                        {
                            DietID = 2,
                            FoodID = 2
                        });
                });

            modelBuilder.Entity("YemekSiparis.Core.Entities.OrderBag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("OrderStatus")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal?>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("OrderBags");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2023, 11, 13, 1, 11, 8, 296, DateTimeKind.Local).AddTicks(6216),
                            CustomerId = 1,
                            DeletedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderDate = new DateTime(2023, 11, 13, 1, 11, 8, 296, DateTimeKind.Local).AddTicks(6216),
                            OrderStatus = 3,
                            Status = 1,
                            TotalPrice = 310m
                        });
                });

            modelBuilder.Entity("YemekSiparis.Core.Entities.OrderDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("FoodID")
                        .HasColumnType("int");

                    b.Property<int>("FoodSize")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("OrderBagID")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("FoodID");

                    b.HasIndex("OrderBagID");

                    b.ToTable("OrderDetails");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2023, 11, 13, 1, 11, 8, 296, DateTimeKind.Local).AddTicks(7364),
                            DeletedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FoodID = 1,
                            FoodSize = 1,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderBagID = 1,
                            Quantity = 1,
                            Status = 1,
                            UnitPrice = 150.00m
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2023, 11, 13, 1, 11, 8, 296, DateTimeKind.Local).AddTicks(7416),
                            DeletedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FoodID = 2,
                            FoodSize = 1,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderBagID = 1,
                            Quantity = 1,
                            Status = 1,
                            UnitPrice = 160.00m
                        });
                });

            modelBuilder.Entity("YemekSiparis.Core.Entities.OrderDetailBeverage", b =>
                {
                    b.Property<int>("BeverageID")
                        .HasColumnType("int");

                    b.Property<int>("OrderDetailID")
                        .HasColumnType("int");

                    b.HasKey("BeverageID", "OrderDetailID");

                    b.HasIndex("OrderDetailID");

                    b.ToTable("OrderDetailBeverages");

                    b.HasData(
                        new
                        {
                            BeverageID = 1,
                            OrderDetailID = 1
                        },
                        new
                        {
                            BeverageID = 2,
                            OrderDetailID = 1
                        });
                });

            modelBuilder.Entity("YemekSiparis.Core.Entities.OrderDetailExtra", b =>
                {
                    b.Property<int>("OrderDetailID")
                        .HasColumnType("int");

                    b.Property<int>("ExtraID")
                        .HasColumnType("int");

                    b.HasKey("OrderDetailID", "ExtraID");

                    b.HasIndex("ExtraID");

                    b.ToTable("OrderDetailExtras");

                    b.HasData(
                        new
                        {
                            OrderDetailID = 1,
                            ExtraID = 1
                        },
                        new
                        {
                            OrderDetailID = 1,
                            ExtraID = 2
                        },
                        new
                        {
                            OrderDetailID = 1,
                            ExtraID = 3
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("YemekSiparis.Core.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("YemekSiparis.Core.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("YemekSiparis.Core.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("YemekSiparis.Core.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("YemekSiparis.Core.Entities.Customer", b =>
                {
                    b.HasOne("YemekSiparis.Core.Entities.AppUser", "AppUser")
                        .WithOne("Customer")
                        .HasForeignKey("YemekSiparis.Core.Entities.Customer", "AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("YemekSiparis.Core.Entities.Food", b =>
                {
                    b.HasOne("YemekSiparis.Core.Entities.Category", "Category")
                        .WithMany("Foods")
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("YemekSiparis.Core.Entities.FoodDiet", b =>
                {
                    b.HasOne("YemekSiparis.Core.Entities.Diet", "Diet")
                        .WithMany("Foods")
                        .HasForeignKey("DietID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("YemekSiparis.Core.Entities.Food", "Food")
                        .WithMany("Diets")
                        .HasForeignKey("FoodID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Diet");

                    b.Navigation("Food");
                });

            modelBuilder.Entity("YemekSiparis.Core.Entities.OrderBag", b =>
                {
                    b.HasOne("YemekSiparis.Core.Entities.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("YemekSiparis.Core.Entities.OrderDetail", b =>
                {
                    b.HasOne("YemekSiparis.Core.Entities.Food", "Food")
                        .WithMany("OrderDetails")
                        .HasForeignKey("FoodID");

                    b.HasOne("YemekSiparis.Core.Entities.OrderBag", "OrderBag")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderBagID");

                    b.Navigation("Food");

                    b.Navigation("OrderBag");
                });

            modelBuilder.Entity("YemekSiparis.Core.Entities.OrderDetailBeverage", b =>
                {
                    b.HasOne("YemekSiparis.Core.Entities.Beverage", "Beverage")
                        .WithMany("OrderDetails")
                        .HasForeignKey("BeverageID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("YemekSiparis.Core.Entities.OrderDetail", "OrderDetail")
                        .WithMany("Beverages")
                        .HasForeignKey("OrderDetailID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Beverage");

                    b.Navigation("OrderDetail");
                });

            modelBuilder.Entity("YemekSiparis.Core.Entities.OrderDetailExtra", b =>
                {
                    b.HasOne("YemekSiparis.Core.Entities.Extra", "Extra")
                        .WithMany("OrderDetails")
                        .HasForeignKey("ExtraID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("YemekSiparis.Core.Entities.OrderDetail", "OrderDetail")
                        .WithMany("Extras")
                        .HasForeignKey("OrderDetailID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Extra");

                    b.Navigation("OrderDetail");
                });

            modelBuilder.Entity("YemekSiparis.Core.Entities.AppUser", b =>
                {
                    b.Navigation("Customer")
                        .IsRequired();
                });

            modelBuilder.Entity("YemekSiparis.Core.Entities.Beverage", b =>
                {
                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("YemekSiparis.Core.Entities.Category", b =>
                {
                    b.Navigation("Foods");
                });

            modelBuilder.Entity("YemekSiparis.Core.Entities.Customer", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("YemekSiparis.Core.Entities.Diet", b =>
                {
                    b.Navigation("Foods");
                });

            modelBuilder.Entity("YemekSiparis.Core.Entities.Extra", b =>
                {
                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("YemekSiparis.Core.Entities.Food", b =>
                {
                    b.Navigation("Diets");

                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("YemekSiparis.Core.Entities.OrderBag", b =>
                {
                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("YemekSiparis.Core.Entities.OrderDetail", b =>
                {
                    b.Navigation("Beverages");

                    b.Navigation("Extras");
                });
#pragma warning restore 612, 618
        }
    }
}
